- output_file: output/Tank_P04.L5X
  input_file: input/Tank_Pxx.L5X
  tag_prefix: P04
  tank_descr: Color Tank 4 - Blue
  has_agitator: true

- output_file: output/Tank_P05.L5X
  input_file: input/Tank_Pxx.L5X
  tag_prefix: P05
  tank_descr: Color Tank 5 - Red
  has_agitator: false
